// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJEuTN_ZcxPDgEENeb90Jkk_VroizzpDM',
    appId: '1:210683609061:web:07024dc7999bd2c919f90c',
    messagingSenderId: '210683609061',
    projectId: 'job-portal-app-17fc1',
    authDomain: 'job-portal-app-17fc1.firebaseapp.com',
    storageBucket: 'job-portal-app-17fc1.appspot.com',
    measurementId: 'G-8FPNZZ3VWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj5259Ci7c_MJ1NrCKHxuw4INvmQRSzOE',
    appId: '1:210683609061:android:9f532c91a50fb9ad19f90c',
    messagingSenderId: '210683609061',
    projectId: 'job-portal-app-17fc1',
    storageBucket: 'job-portal-app-17fc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqkCGSd_geFfiQvLeK1EU_SVxw7aDflSc',
    appId: '1:210683609061:ios:8d4bf93ba0d8e1a619f90c',
    messagingSenderId: '210683609061',
    projectId: 'job-portal-app-17fc1',
    storageBucket: 'job-portal-app-17fc1.appspot.com',
    iosClientId: '210683609061-tt3kh30re4ih3fk3no814v9eul5upshg.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobportalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqkCGSd_geFfiQvLeK1EU_SVxw7aDflSc',
    appId: '1:210683609061:ios:8d4bf93ba0d8e1a619f90c',
    messagingSenderId: '210683609061',
    projectId: 'job-portal-app-17fc1',
    storageBucket: 'job-portal-app-17fc1.appspot.com',
    iosClientId: '210683609061-tt3kh30re4ih3fk3no814v9eul5upshg.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobportalapp',
  );
}
